
import os

from dotenv import load_dotenv
from typing import Optional
from pathlib import Path

from pydantic_ai import Agent
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.ollama import OllamaProvider
from pydantic_ai.tools import Tool

from pydantic_ai.common_tools.tavily import tavily_search_tool

load_dotenv()

class AgentModel:
    def __init__(self):
        self.model_name = os.getenv("OLLAMA_MODEL")
        self.ollama_base_url = os.getenv("OLLAMA_BASE_URL")
        self.agent_tools = AgentTools()
    
    def get_ollama_model(self):
        return OpenAIChatModel(
            model_name=self.model_name,
            provider=OllamaProvider(base_url=self.ollama_base_url),
        )
    
    def build_agent(self):
        model = self.get_ollama_model()
        return Agent(
            model, 
            tools=self.agent_tools.get_tools(),
            system_prompt="""You are a helpful AI assistant with access to tools. 
            
            IMPORTANT: When users ask you to perform tasks, you should USE YOUR TOOLS to complete them, not write code or provide instructions.
            
            Available tools:
            - tavily_search: Search the web for real-time information
            - create_text_document: Create text files with llm-generated content
            
            CRITICAL: When using create_text_document, you MUST provide actual content in the 'content' parameter. 
            Do NOT pass empty strings or null values. The content should be the actual text you want to save.
            
            For example, if a user asks you to "search for news and create a file", you should:
            1. Use tavily_search to find the information
            2. Take the search results and format them into readable text
            3. Use create_text_document with the formatted text as the content parameter
            4. Provide a summary of what you found and created
            
            Always use your tools to complete tasks directly and ensure all parameters have meaningful values."""
        )
    
    def invoke(self, prompt: str):
        agent = self.build_agent()
        response = agent.run_sync(prompt)
        return response.output
    
class AgentTools:
    def __init__(self):
        self.tavily_search_api_key = os.getenv("TAVILY_API_KEY")
        self.output_dir = Path("output")
        self.output_dir.mkdir(exist_ok=True)
    
    def get_tools(self):
        return [
            self.tavily_search(),
            self.create_text_document_tool()
        ]
    
    def tavily_search(self):
        """
        Search the web for information.
        """
        return tavily_search_tool(self.tavily_search_api_key)

    def create_text_document_tool(self):
        """
        Create a text document with LLM-generated content.
        """
        @Tool
        def create_text_document(
            filename: str,
            content: str,
            directory: Optional[str] = None
        ) -> str:
            """
            Create a text file with the specified content. Use this tool when the user asks you to save information to a file, create a document, or write content to a .txt file.
            
            Args:
                filename: Name of the file to create (should include .txt extension)
                content: The text content to write to the file (this should be the actual text content generated by the LLM, not empty)
                directory: Optional subdirectory within the output folder
            
            Returns:
                Success message with file path
            """
            try:
                # Validate content
                print(f"Content: {content}")
                if not content or content.strip() == "":
                    return f"Error: Content cannot be empty. Please provide actual text content to write to the file."
                
                # Determine the output path
                if directory:
                    output_path = self.output_dir / directory
                    output_path.mkdir(exist_ok=True)
                else:
                    output_path = self.output_dir
                
                # Ensure filename has .txt extension
                if not filename.endswith('.txt'):
                    filename += '.txt'
                
                file_path = output_path / filename
                
                # Write content to file
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                
                return f"Successfully created text file: {file_path.absolute()}\nFile size: {len(content)} characters"
                
            except Exception as e:
                return f"Error creating text file: {str(e)}"
        
        return create_text_document
