import os

from typing import Optional
from pathlib import Path

from pydantic_ai.common_tools.tavily import tavily_search_tool
from pydantic_ai.tools import Tool


class AgentTools:
    def __init__(self):
        self.tavily_search_api_key = os.getenv("TAVILY_API_KEY")
        self.output_dir = Path("output")
        self.output_dir.mkdir(exist_ok=True)

    
    # ================================
    # Web Search Tools
    # ================================
    
    def tavily_search(self):
        """
        Search the web for information.
        """
        return tavily_search_tool(self.tavily_search_api_key)

    # ================================
    # Document Handling Tools
    # ================================

    def create_text_document_tool(self):
        """
        Create a text document with LLM-generated content.
        """
        @Tool
        def create_text_document(
            filename: str,
            content: str,
            directory: Optional[str] = None
        ) -> str:
            """
            Create a text file with the specified content. Use this tool when the user asks you to save information to a file, create a document, or write content to a .txt file.
            
            Args:
                filename: Name of the file to create (should include .txt extension)
                content: The text content to write to the file (this should be the actual text content generated by the LLM, not empty)
                directory: Optional subdirectory within the output folder
            
            Returns:
                Success message with file path
            """
            try:
                # Validate content
                print(f"Content: {content}")
                if not content or content.strip() == "":
                    return f"Error: Content cannot be empty. Please provide actual text content to write to the file."
                
                # Determine the output path
                if directory:
                    output_path = self.output_dir / directory
                    output_path.mkdir(exist_ok=True)
                else:
                    output_path = self.output_dir
                
                # Ensure filename has .txt extension
                if not filename.endswith('.txt'):
                    filename += '.txt'
                
                file_path = output_path / filename
                
                # Write content to file
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                
                return f"Successfully created text file: {file_path.absolute()}\nFile size: {len(content)} characters"
                
            except Exception as e:
                return f"Error creating text file: {str(e)}"
        
        return create_text_document
