"""Change user_id field type do foreingkey

Revision ID: 6b18cf9961f4
Revises: e9b8a096a9c9
Create Date: 2025-10-28 19:56:00.555973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b18cf9961f4'
down_revision: Union[str, Sequence[str], None] = 'e9b8a096a9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
